-- MySQL Script generated by MySQL Workbench
-- 07/03/16 23:39:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TipoRol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoRol` (
  `idTipoRol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrera` (
  `idCarrera` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreCarrera` VARCHAR(100) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UEA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UEA` (
  `idUEA` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Carrera_idCarrera` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUEA`),
  INDEX `fk_UEA_Carrera1_idx` (`Carrera_idCarrera` ASC),
  CONSTRAINT `fk_UEA_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `correo` VARCHAR(45) NULL,
  `sexo` TINYINT(1) NULL,
  `fechaNacimiento` DATE NULL,
  `contraseña` BLOB NULL,
  `tipoRol_idTipoRol` INT UNSIGNED NOT NULL,
  `uEA_idUEA` INT NOT NULL,
  `Carrera_idCarrera` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAutor`),
  INDEX `fk_tablaAutor_tablaTipoRol_idx` (`tipoRol_idTipoRol` ASC),
  INDEX `fk_Autor_UEA1_idx` (`uEA_idUEA` ASC),
  INDEX `fk_Autor_Carrera1_idx` (`Carrera_idCarrera` ASC),
  CONSTRAINT `fk_tablaAutor_tablaTipoRol`
    FOREIGN KEY (`tipoRol_idTipoRol`)
    REFERENCES `mydb`.`TipoRol` (`idTipoRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_UEA1`
    FOREIGN KEY (`uEA_idUEA`)
    REFERENCES `mydb`.`UEA` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera`)
    REFERENCES `mydb`.`Carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recurso` (
  `idRecurso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreRecurso` VARCHAR(100) NULL,
  `descripcionRecurso` MEDIUMTEXT NULL,
  `fechaPublicacion` DATE NULL,
  `calificacionPromedio` INT NULL,
  `url` VARCHAR(300) NULL,
  `licencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idRecurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `idComentario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(500) NULL,
  `recurso_idRecurso` INT UNSIGNED NOT NULL,
  `Autor_idAutor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_tablaComentarios_tablaRecurso1_idx` (`recurso_idRecurso` ASC),
  INDEX `fk_Comentarios_Autor1_idx` (`Autor_idAutor` ASC),
  CONSTRAINT `fk_tablaComentarios_tablaRecurso1`
    FOREIGN KEY (`recurso_idRecurso`)
    REFERENCES `mydb`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentarios_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Valoracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Valoracion` (
  `idValoracion` INT NOT NULL,
  `valoracion` DECIMAL(10,0) NULL,
  `recurso_idRecurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idValoracion`),
  INDEX `fk_tablaValoraciones_tablaRecurso1_idx` (`recurso_idRecurso` ASC),
  CONSTRAINT `fk_tablaValoraciones_tablaRecurso1`
    FOREIGN KEY (`recurso_idRecurso`)
    REFERENCES `mydb`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Publicacion` (
  `idPublicacion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Autor_idAutor` INT UNSIGNED NOT NULL,
  `Recurso_idRecurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `fk_tablaPublicaciones_tablaAutor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_tablaPublicaciones_tablaRecurso1_idx` (`Recurso_idRecurso` ASC),
  CONSTRAINT `fk_tablaPublicaciones_tablaAutor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tablaPublicaciones_tablaRecurso1`
    FOREIGN KEY (`Recurso_idRecurso`)
    REFERENCES `mydb`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RecursoUEA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RecursoUEA` (
  `idRecursoUEA` VARCHAR(45) NOT NULL,
  `UEA_idUEA` INT NOT NULL,
  `Recurso_idRecurso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRecursoUEA`),
  INDEX `fk_RecursoUEA_UEA1_idx` (`UEA_idUEA` ASC),
  INDEX `fk_RecursoUEA_Recurso1_idx` (`Recurso_idRecurso` ASC),
  CONSTRAINT `fk_RecursoUEA_UEA1`
    FOREIGN KEY (`UEA_idUEA`)
    REFERENCES `mydb`.`UEA` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RecursoUEA_Recurso1`
    FOREIGN KEY (`Recurso_idRecurso`)
    REFERENCES `mydb`.`Recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
